### ISSUE TITLE
add "walker globals" command? 

### ISSUE THREAD

**Issue by mbaersch** [elbwalker/walker.js#129]
**Is your feature request related to a problem? Please describe.**
AFAIK populating global values requires to add elements to the DOM and there is no way to set globals by using JavaScript.

**Describe the solution you'd like**
adding a command to change / add walker key / value pairs in globals. 

**Describe alternatives you've considered**
adding stuff to the DOM dynamically - that´s what I do at the moment.

**Comment by alexanderkirtzel** [comment]
We should do that. How about taking it one step further with `walker config`?
Right now you can init Elbwalker with a config to set consent, elbLayer, pageview, prefix, and version. We should also add globals here.

`elb("walker config", { globals: { language: "en" }, pageview: false });`

**Comment by mbaersch** [comment]
that would be even better... At least for most sites. Having an additional command to change globals whenever suitable (like in a single page app) still might make sense.
