### ISSUE TITLE
Context value are not sent within an entity

### ISSUE THREAD

**Issue by b-barry** [elbwalker/walker.js#183]
**Describe the bug**
Context value are not sent 

**To Reproduce**
1. Go to 'https://playcode.io/1276157'
2. Click on 'Get access to our one-time sale'
4. See console log

**Expected behavior**
The right console , the context should contain a not empty object

**Comment by alexanderkirtzel** [comment]
Hey,

I can reproduce it. The context is not set.
Currently, context is only considered from the parents of an entity, not from the triggering action element.

If you want to try two different buttons, you would set a different context around the button, not the complete entity. Therefore let's change it.

In the meantime, you can set context on an entity's parent if possible.
