### ISSUE TITLE
GA4 implementation doesn't make a network request

### ISSUE THREAD

**Issue by danlin604** [elbwalker/walker.js#186]
**Describe the bug**
I am unable to successfully make a network request following Walker's GA4 examples.

**To Reproduce**
I've tried a few variations. I'll start with the default working example from GA4 (without Walker.js) and show the two other non-working examples. 

Working example
```HTML
<script>
    window.dataLayer = window.dataLayer || [];
    function gtag() { dataLayer.push(arguments); }
    gtag('js', new Date());

    gtag('config', 'G-1234567890');
</script>
```

Walker.js example
Script errors out at the import due to missing ) in parenthetical. I resolved the error and no network request is triggered still.
```HTML
<script>
    const config /* : DestinationGoogleGA4.Config */ = {
        debug: true, // Enable debug mode
        custom: {
            measurementId: 'G-1234567890', // Required
        },
    };

    // Make sure to initialize the elb function once.
    function elb() {
        (window.elbLayer = window.elbLayer || []).push(arguments);
    }

    // Upload the dist/index.mjs on your own server
    const destination = ( // Code errors out here
        await import(
            'https://cdn.jsdelivr.net/npm/@elbwalker/destination-web-google-ga4/dist/index.mjs'
        )
    ).default;

    elb('walker destination', destination, config);
</script>
```

Walker.js example
```JavaScript
const config /* : DestinationGoogleGA4.Config */ = {
    debug: true, // Enable debug mode
    custom: {
        measurementId: 'G-1234567890', // Required
    },
};

elb('walker destination', DestinationGoogleGA4, config);  
```

**Expected behavior**
A network request to google analytics should be made on page visit.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 110.0

**Comment by alexanderkirtzel** [comment]
Thanks for the detailed description!
Is GA4 present on that page from some other implementation (hard coded or via your CMP)?

Otherwise, you can add `loadScript: true` to the config. This way the destination makes sure to load the required libraries, once an event gets pushed.

You should have some events like `['config', 'G-1234567890']` in your dataLayer but gtag not available yet, right?

**Comment by danlin604** [comment]
I'll give that a try, thanks!

**Comment by danlin604** [comment]
Sorry, haven't revisited this yet. Been occupied with other items.

**Comment by alexanderkirtzel** [comment]
Solved as discussed
