### ISSUE TITLE
Destination request : Plausible.io

### ISSUE THREAD

**Issue by Jojoker33** [elbwalker/walker.js#68]
**Is your feature request related to a problem? Please describe.**
As nowadays, analytics tool needs to be GDPR, CCPA or PECR compliant in order to be used in some countries : walker.js should be able to offer destinations which  respect those compliance. 

**Describe the solution you'd like**
Having [Plausible analytics](https://plausible.io/) as destination for GDPR, CCPA and PECR compliance.

**Comment by alexanderkirtzel** [comment]
Totally agree. I'll add Plausible as a destination.

Would you like to have all events sent to Plausible automatically & by default or would you prefer to define a mapping to fine-tune which events are sent?

```json
"promotion": {
  "impression": {
    "event": "promotion_impression",
    "other": "configuration settings"
  },
  "click": {
    "event": "promotion_click"
  }
}
```

I'll also add an optional part for the init. You might not want the walker.js to add the script by default.
If you've any requirements to this destinations just let me know.

**Comment by Jojoker33** [comment]
I would prefer the mapping solution one, like this it's easier to handle

**Comment by alexanderkirtzel** [comment]
We've moved the destinations to independent npm packages and added Plausible

See @elbwalker/destination-web-plausible at NPM

We've added the option to set a mapping but by default all events gets pushed
