### ISSUE TITLE
Independent child event and related components only properties

### ISSUE THREAD

**Issue by Jojoker33** [elbwalker/walker.js#77]
**Is your feature request related to a problem? Please describe.**
When trigger a child component event, parents event are also triggered a the same time

**Describe the solution you'd like**
The possibility to have isolated child component, context event from the parent, larger context.

**Describe alternatives you've considered**
New scoped properties: the possibility  to have some properties only available for related components so when the an event bubble up, add more specific context, info along the way 

**Additional context**
for more context please this [stackblitz](https://stackblitz.com/edit/web-platform-p8rez7?devToolsHeight=33&file=index.html)

**Comment by alexanderkirtzel** [comment]
It's definitely a point once you use walker way more. We called them **action filter** and described them in the docs, https://docs.elbwalker.com/walker/action-filter

```html
<!-- setting a filter for an entity -->
<div data-elb="foo">
  <div data-elb="bar" data-elbaction="load:hello(bar)">
    only the bar hello event fires.
  </div>
</div>
```

You'll only get the `bar hello` event without the `foo hello` in this example. You could separate them by comma as well for multiple filters.

Hope this helps!
