### ISSUE TITLE
Nested entites : keyword inside closest parent for data sharing

### ISSUE THREAD

**Issue by Jojoker33** [elbwalker/walker.js#81]
**Is your feature request related to a problem? Please describe.**
By example, a list of products  contained in a labeled section,  you might be interested in capturing that the user clicked inside a specific section ( e.g: section's ID or section label ) In addition to clicked product 

**Describe the solution you'd like**
With a similar usage  as [globals](https://docs.elbwalker.com/walker/globals), properties will available for the closest nested entities or all the nested entities close or far deep inside the same dom tree branch

**Additional context**
from the example of [nested entitles doc ](https://docs.elbwalker.com/walker/nested-entities) : in the situation where the baby entity send an event be able to have additional information provided thanks to the daughter entity

**Comment by Jojoker33** [comment]
Is this feature in consideration or need more explanation from my side ?

**Comment by alexanderkirtzel** [comment]
Do you mean properties that are listed directly on a parent element? Those are already considered.

```html
<div data-elb-e="parent:value">
  <div data-elb-e="not:considered"></div>
  <div data-elb="e" data-elb-e="regularly:inside" data-elbaction="click">click me</div>
</div>
```
The event will look like `data:{parent: 'value', regularly: 'inside'}`

Or can you give an example of the code and/or result you want to see?

**Comment by Jojoker33** [comment]
Hi, what's the behaviour,  if both, parent and children,  have their own entity scope ? Is it possible to have a scope parent sharing data with a nested scope without using globals ?

**Comment by alexanderkirtzel** [comment]
Both are always having their own scope. Sharing data could be done by either using globals or duplicate definitions, see data-elb-parent & data-elb-child

```html
<div data-elb="parent" data-elb-parent="foo:bar" data-elb-child="foo:bar" >
  <div data-elb="child">click me</div>
</div>
```

Within the parent entity, the child is nested and therefore the data accessible. But not the other way around. I haven't done any performance testings in detail yet and therefore didn't wanted to add the `parent` prop to an event.

Can you live with the recommended idea? Or if not, can you share more details about your case?

**Comment by alexanderkirtzel** [comment]
How about the `data-elbcontext` feature? We don't want to pollute the globals, since they are relevant for every single event. But we wan't to learn more about the context around us. All entities inside a defined context want to know about this context. A context could be a position or test it's embedded in.

```html
<div data-elbcontext="test:engagement" data-elbglobals="plan:paid">
  <div data-elbcontext="recommendation:smart_ai">
    <div
      data-elb="promotion"
      data-elbaction="click"
      data-elb-promotion="title:click me"
    >
      click me
    </div>
  </div>
</div>
```

Would result in 
```json
{
    "event": "promotion click",
    "data": { "title": "click me" },
    "globals": { "plan": "paid" },
    "context": {
      "test": "engagement",
      "recommendation": "smart_ai",
    },
  }
```

The `data` is only relevant for the specific entity, the `context` is relevant for ever entity inside a special context that could affect the adoption and the `globals` should be known for every single event on a page.

Would this solve your issue?

**Comment by alexanderkirtzel** [comment]
implemented, see https://github.com/elbwalker/walker.js/releases/tag/v1.5.2

**Comment by oliverartmannn** [comment]
> 

Hi Alex, having multiple contexts in an object will probably lose the order/relationship to each other.

Maybe your example should result in something like the below:

`{
    "event": "promotion click",
    "data": { "title": "click me" },
    "globals": { "plan": "paid" },
    "context": [
        {
          "test": "engagement",
          "parent": null,
        },
        {
          "recommendation": "smart_ai",
          "parent": {
              "test": "engagement",
          },
        },
      ]
  }`

or 

`"context": "test:engagement|recommendation:smart_ai|..."`

**Comment by alexanderkirtzel** [comment]
Memorizing the context's order sounds like a good idea.

```
"context": [
    { "recommendation": "smart_ai" }
    { "test": "engagement", "another": "value" },
]
```

Recommendation was closer than test. Besides test there was also another `data-elbcontext="test:engagement;another:value"`

They are parents by design. What do you think?

**Comment by alexanderkirtzel** [comment]
EDIT: context on the same level will have the same index. The snippet above would override values. Instead of `acc[i]` one could use an array value instead.
