### ISSUE TITLE
Documentation: SSR framework behaviour

### ISSUE THREAD

**Issue by Jojoker33** [elbwalker/walker.js#95]
**Is your feature request related to a problem? Please describe.**
 In SSR framework : 

- elbWalker usage requires dynamic import otherwise it create an  **_error - ReferenceError: document is not defined_**

**Describe the solution you'd like**
Update documentations to help with ssr requirement

**Comment by alexanderkirtzel** [comment]
Where do you want to use the walker.js? It's made for the browser and requires the window und document environment to setup event listeners etc.

Can you please give some more details?

**Comment by Jojoker33** [comment]
In SSR framework such as Next, Nuxt or Sveltekit by example, the rendering is done on the server side which doesn't have object such as Document or window until being on the browser. As more and more, front-end development trend to go to a SSR solution for performance UX improvement, some awareness should be shared about the fact it would have some issue in the ssr, exactly because of the window and document requirement.

Please check this simple nextjs example with simple workaround solution:
[document isssue example ](https://codesandbox.io/s/ssr-issue-example-4ipbfs?file=%2Fpages%2Findex.js
)

**Comment by deepskydata** [comment]
+1 - same problem in sveltekit atm.

**Comment by alexanderkirtzel** [comment]
Walker.js is currently built for frontend usage, and an instance should be created client-side not server-side.
When calling Elbwalker() window- or document-based operations are performed e.g. init triggers or the elbLayer.
However, there was an issue with the global vars used for document and window. Those are fixed.
I'd suggest moving init to the Layout or a Component. With the fix, it should be possible. To fully support server-side usage & destinations I need to better understand requirements. Feel free to reach out. Fix will be released with 1.6, coming soon.
